sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "6"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
    - node_js: "6"
cache:
  directories:
  - node_modules
notifications:
  email: false
